name: "[CI]tag push"
on:
  push:
    tags:
      - "v1.*"
  workflow_dispatch:
    inputs:
      tag:
        description: '`vx.y.z-릴리즈` 형태로 버전을 입력해주세요. `vx.y.z`도 가능합니다.'
        required: true
        default: 1.2.3

env:
  SERVICE: ${{ github.repository }}

jobs:
  
  condition_check:
    runs-on: ubuntu-latest
    outputs:
      NOT_FIRST_TAG: ${{ steps.job1.outputs.not_first_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: if master, exit
        if: github.event_name == "workflow_dispatch" 
        run: |
          if [ ${{ github.ref }} = refs/heads/master ]
            then exit 1
          fi
      - name: if not same branch, exit
        if: github.event_name == "workflow_dispatch" 
        run: |
          if [ $(echo ${{ github.event.inputs.tag }} | cut -c 2-6) != $(cat src/VERSION | cut -c 2-6) ]
            then exit 1
          fi
      - name: totally same version, redeploy dockerhub
        id: job1
        run: |
          if [ ${{github.event_name}} == "workflow_dispatch" ]
            then
              echo "::set-output name=TAG::${{ github.event.inputs.tag }}"
              if [ $(cat src/VERSION) = ${{ github.event.inputs.tag }} ]
                then echo "::set-output name=not_first_tag::true"
                else echo "::set-output name=not_first_tag::false"
              fi
            else
              echo "::set-output name=TAG::${{ github.event.client_payload.version }}"
              if [ $(cat src/VERSION) = ${{ github.event.client_payload.version }} ]
                then echo "::set-output name=not_first_tag::true"
                else echo "::set-output name=not_first_tag::false"
              fi
          fi
          

  update_master_branch_version_file:
    needs: condition_check
    runs-on: ubuntu-latest
    if: ${{ needs.condition_check.outputs.NOT_FIRST.TAG }} = 'false'
    steps:
      - name: update master version
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          event-type: update_master_version
          client-payload: '{"version": "${{ needs.condition_check.outputs.TAG }}"}'

  update_local_version_file:
    needs: condition_check
    runs-on: ubuntu-latest
    if: ${{ needs.condition_check.outputs.NOT_FIRST.TAG }} = 'false'
    env:
      VERSION: ${{ needs.condition_check.outputs.TAG }}
    steps:
      - name: set branch env
        run: |
          echo "::set-env name=BRANCH::$(echo ${{ env.VERSION }}| cut -c 2-6 | awk '{print "release-"$1}')"
          echo "::set-output name=BRANCH::$(echo ${{ env.VERSION }}| cut -c 2-6 | awk '{print "release-"$1}')"
      - name: task
        uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git checkout ${{ github.ref }}
          echo ${{ env.VERSION }} > src/VERSION
          git add .
          git commit -m "[CI/CD] release version ${{ env.VERSION }}"
          git tag ${{ env.VERSION }} 
          git push --atomic origin ${{ env.BRANCH }} ${{ env.VERSION }}

  pypi:
    if: github.repository_owner == 'spaceone-dev' && ${{ needs.condition_check.outputs.NOT_FIRST.TAG }} = 'false'
    needs: [condition_check, update_local_version_file]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git pull
          git checkout ${{ needs.update_local_version_file.outputs.BRANCH }}
      - name: set version
        run: |
          echo ${{ needs.condition_check.outputs.TAG }} | cut -c 2- |sed -e 's/-//g' > src/VERSION
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel twine
      - name: Build
        run: |
          cd src
          python setup.py sdist bdist_wheel
      - name: Upload Pypi
        id: upload
        run: |
          cd src
          twine upload dist/*.whl --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --verbose

  docker:
    needs: [condition_check, update_local_version_file, pypi]
    if: github.repository_owner == 'spaceone-dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git pull
          git checkout ${{ needs.update_local_version_file.outputs.BRANCH }}
      - name: set service env
        run: |
          echo "::set-env name=SERVICE::$(echo ${{ env.SERVICE }} | cut -c 14-)"
      - name: versioning by the convetion
        run: |
          echo "::set-env name=VERSION::$(echo ${{ needs.condition_check.outputs.TAG }} | cut -c 2- | sed -e 's/-//g')"
      - name: set version file
        run: |
          echo ${{ env.VERSION }} > src/VERSION
      - name: set repo env
        run: |
          if [ $VERSION =~ ^[0-9]\.[0-9]\.[0-9]dev(.*)$ ]
            then echo "::set-env name=ORGANIZATION::pyengine"
            else echo "::set-env name=ORGANIZATION::spaceone"
          fi
      - name: Upload docker
        uses: docker/build-push-action@v1
        with:
          path: .
          repository: ${{ env.ORGANIZATION }}/${{ env.SERVICE }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ env.VERSION }}

  notify_to_slack:
    if: github.repository_owner == 'spaceone-dev'
    needs: [condition_check, update_local_version_file, pypi, docker]
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
